services:
  grafana:
    user: root
    container_name: 'ik-panel-plugin'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-12.3.0}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 5500:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/ik-panel-plugin
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/ik-panel-plugin

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.ik-panel-plugin:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: ik-panel-plugin
